# -*- coding: utf-8 -*-
"""superstore.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oy7djjDR0aGag6QAzP3jqzJj97qqsK2-
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("vivek468/superstore-dataset-final")

print("Path to dataset files:", path)

import pandas as pd
data= pd.read_csv(path + "/Sample - Superstore.csv",encoding='latin1')
data

data.columns

data.info()

data.drop('Row ID',axis =1,inplace=True)

data

data.isna().sum()

data.isnull().sum()

data['Order Date']=pd.to_datetime(data['Order Date']).dt.strftime('%d-%m-%Y')

data['Ship Date'] = pd.to_datetime(data['Ship Date']).dt.strftime('%d-%m-%Y')

data

data['Ship Mode'].value_counts()

data['Category'].value_counts()

data['Sales'].describe()

data['Sales'].sum()

data['Quantity'].sum()

data['Discount'].sum()

data['Profit'].sum()

data['Profit Margin'] = data.apply(lambda row : row['Profit'] / row['Sales'] if row['Sales'] != 0 else 0 , axis =1)

data

data.groupby('Ship Mode')['Sales'].sum().reset_index()

data['Category'].value_counts().reset_index()

data.drop_duplicates(inplace=True)

data

data['Order Date'].unique()

data['Ship Date'].unique()

data['Segment'].value_counts()

data['Region'].value_counts()

import matplotlib as plt
data['Ship Mode'].value_counts().plot.pie(autopct='%.2f%%')

data['Category'].value_counts().plot.pie(autopct='%.2f%%')

data.to_csv("superstore.csv")

